### ISSUE TITLE
cleanup tracking

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1223]
Things to clean:
- [x] Remove bots.zip release artifact  (the all-platform.zip is installed on bots)
- [x] Remove 'triplea-headless' executable that is bundled with the game distribution (on at least linux), it is  broken
- [x] Remove ant build script, no longer used (https://github.com/triplea-game/triplea/issues/601)

**Comment by DanVanAtta** [comment]
removed bots: https://github.com/triplea-game/triplea/pull/1392
