### ISSUE TITLE
TripleA Roadmap

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#1233]
This is an issue, to remember all of our goals for the next big releases.
- [ ] Migrate UI to JavaFX (1.10)
- [ ] Savegame-format without serialization (YAML, JSON, XML, etc.)(2.0)
- [ ] Network Connection without usage of Reflection(1.11+)
- [ ] MapXMLs without reflection(1.11+)

**Comment by DanVanAtta** [comment]
Nope, but note when when we got to save games that are compatible, the release number will be `2.<build_number>`

3rd one is likely a goal for the following release, not the very next.

**Comment by RoiEXLab** [comment]
Ok I'll edit the issue tomorrow

**Comment by Cernelius** [comment]
Will the new savegame be smaller and faster to start in a hosted game (like less waiting time between clicking on start and the game being ready to be played)?
I notice that the waiting times now about multiplies by the number of peeps, making a bit tiresome to keep reloading multis with frequent disconnections. Also it is a problem when someone doesn't have the map, and you have to wait to crash.
Also, it much depends if somebody has very slow connection, and you don't know who the hold-up is.

What does "MapXMLs without reflection" means??

**Comment by RoiEXLab** [comment]
I don't know, maybe it will be faster, maybe not... But What it's definitely doing is work throughout versions, meaning that you will be able to load this new savegame in any newer version of the game and we as developers no lonher have to care about potentially breaking savegames.
MapXML s are read as a string, meaning they tell triplea which methods to execute. This is not good, since if anything is ever renamed, we have to update all maps to implement the new changes. The goal would be to have some keywords or similar which then are evaluated in code and calling the right method

**Comment by Cernelius** [comment]
So, basically, the only 1 release-related advantage is saving the about 20 MB for having the old jars for the old savegames? I was hoping this was something related to reducing savegame size; oh well.

**Comment by RoiEXLab** [comment]
That's not said...
The thing is we/I have no idea how big savegames are going to be in the future, since we aren't even sure on what format to use.
Best Case: We are currently saving way too much information and almost everything can be replaced with references e.g. Map:classic WW2 moved: e1->a2 battled: d5
Worst Case (Very unlikely): We are only able to replace everything in text form which increases the file size by 50%, but at least the savegames are compatible...

**Comment by DanVanAtta** [comment]
@RoiEXLab , it's really ambitious to keep track of all 4 of those major projects in this ticket. Let's move them to projects or milestones. It's good practice to make sure that any issue is always reasonably actionable. Completing 4 giant project is not very practical, this results in even more tickets laying around that we cannot close.

The creation of milestones or projects is a good exit criteria IMO for this ticket.
