### ISSUE TITLE
Build And Release Automation Project

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#216]
### Project Goal

After pushing a tag to git or merging a pull request, the following will automatically happen:
- tests are run
- (merge case only) generate an automated version number and push a tag with that version number
- builds release artifacts and push them to github releases (as a prerelease), these artifacts are:
 - shadow jar (triplea.jar bundled with all dependencies)
 - windows installer
 - unix installer
 - mac installer
 
### Project Milestones
- [x] Builder bot account created and given write access
- [x] Automated push to github releases of shadowjar  (#248 )
- [x] Automatic pushes of a tag after merge (#248)
- [x] Scripted (install4j) build of OS installers on linux (#218)
- [x] Automated push of all OS installers to github releases

**Comment by DanVanAtta** [comment]
Automated shadow jar pushes now working:

![screenshot from 2015-10-30 03 23 07](https://cloud.githubusercontent.com/assets/12397753/10843552/eb26c3ea-7eb6-11e5-9ffc-4c6706f730b7.png)

**Comment by DanVanAtta** [comment]
Good work getting the install4j stuff finished @gaborbernat 

After some tweaks to travis (#261), we just had our first automatic build and release of the installation artifacts. Will open up a new ticket to follow up with QA of the artifacts and further testing.

Below is a screenshot of the first fully automated release triggered by merging a PR:

![automated_release](https://cloud.githubusercontent.com/assets/12397753/10931222/9047ab66-827a-11e5-8076-883007fcaa06.png)
