### ISSUE TITLE
Build installers and release process QA and follow up

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#262]
- [x] Fix cannot find root folder warning message : #260
- [ ] Verify Mac DMG installation
- [x] Verify Windows install
- [x] Verify Linux install
- [ ] Verify bot install
- [x] Verify server lobby install
- [ ] Verify all platforms zip
- [ ] Ensure wiki docs are updated to reflect the latest
- [ ] Source forge announcement that new releases will be automatically available
- [ ] Make sure old jar game compatibility still works
- [x] Fix asset loader bug #338 
- [x] Simplify bundled/non-bundled download process #354 
- [x] Fix sound #339 
- [x] Fix map asset loading order regression bug #338

Release URL:
http://github.com/triplea-game/triplea/releases/

**Comment by DanVanAtta** [comment]
Redundant to #382
