### ISSUE TITLE
Moderator Toolbox 2.0  TODO Items

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4894]
Issue to track post-merge TODO items.

- [x] Use Bcrypt hashing for api keys
- [x] Ignore 'x-forwarded-header', just use "remoteAddr" only (instead of using either-or, just use the one)
- [x] ~~better error messaging when duplicate keys exist~~
- [x] ~~double check readme content captures key design patterns~~
- [x] ~~Address any post-merge feedback from: https://github.com/triplea-game/triplea/pull/4899~~
- [x] Verify no http client retry of bad API keys 
- [ ] add a 'super-mod' column to moderators tab
- [ ] Remove main method on `ShowToolboxController` 
- [ ] Use non-deprecated encode body method for feign client requests: https://github.com/triplea-game/triplea/pull/4872/files/f0408aae6c2295ce07ae2bb1e71fea1ba3e0d8c7#diff-365aec5f85c5be0630d5ae833a6bca3c
- [ ]  See if we can remove `Calendar` instance when getting timestamps from `ResultSet`. IE, instead of: `resultSet.getTimestamp(columnName, calendar)`, use: `resultSet.getTimestamp(columnName)`
- [ ] disable 'remove mod' and 'add super-mod' button for super mods
- [ ] disable user name ban button if user name is banned
- [ ] verify behavior of multiple user bans
- [ ] verify behavior when a registered user has their name banned 
- [ ] use proper parent window. For some pop-ups the lobby window comes to the front rather than the toolbox window
- [ ] verify always on top set appropriately for dialogs.
- [ ] verify there are tooltips on any disabled button to explain why they are disabled
- [ ] do not allow double moderator adds, when typing in 'add moderator' name, do not enable the submit button if the user is already a moderator. Display a toast message if this happens.

**Comment by DanVanAtta** [comment]
Closing, moved all open todo tasks to unit-scroller project: https://github.com/triplea-game/triplea/projects/11
