### ISSUE TITLE
Updated Map Downloads - Bug Tracking

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#517]
A master tracking ticket for the various new problems we discover with the updated download. Larger problems can be mentioned here or as added a ticket, smaller ones can be simply mentioned here

- [ ] # 516  (at least Win7) Download Window opened multiple times does not come to the front
- [x] # 508 Cannot delete maps on windows after they have been scanned by the available game parser. Easiest to see by opening a game and trying to delete any map, the background parser will have hit all those zip files aleady and windows is then unable to delete the resources (resource already in use) 
- [x] Can open multiple download map windows, should be limited to just one (and in that case any already open window also brought to the front)

**Comment by DanVanAtta** [comment]
#516 is tracking the one outsanding issue, resolving.
