### ISSUE TITLE
Unit Scroller TODO

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5181]
- [ ] Sort units in the avatar image for infantry to be first, then tanks, then air
- [ ] Clicking a unit should 'wake' the unit
- [ ] Fix initial width of sidebar (EG: Napoleonic Empries)

**Comment by ron-murhammer** [comment]
@DanVanAtta You should probably use the same sort that the battle calc uses for ordering units.

**Comment by Cernelius** [comment]
>Fix initial width of sidebar (EG: Napoleonic Empries)

Not sure if I've been misunderstood. The initial width of the sidebar, determined only by the wideness of the small map, is fine. Also, it would be better if you can shrink the right side bar always back to those starting dimensions.

Just this feature should either be less minimally wide, or cut itself a better way (cut the units image instead of the buttons).

**Comment by DanVanAtta** [comment]
@Cernelius if the small map were tiny, should we have absolutely tiny controls or controls that are cut-off and not usable? How to handle that situation. I think implicit to unit scroller, some space is needed. The side-bar being wide and narrow on some maps is a bit inconsistent. I don't think it's really a designed feature that it be as wide as the small map, just more an artifact of how it was coded and the technology.

**Comment by DanVanAtta** [comment]
To be explicit, if we can make the unit scroller narrower, that would be a win. There will eventually be a minimum between the small map or scroller and one of them will eventually become the limiting factor. Saying scroller to be allowed minimum zero space means the controls would not be usable, as well as any other view items in the side bar. It's also really questionable if unit stats are that narrow, there are certainly display issues present there as well.

In general a lot of the UI sizing is a mess, artifact of using a technology that is so old. So I would disagree that the side bar sizing is 'fine', as one existing problem I'd point to the unit stats table that is often unusable until expanded.

**Comment by Cernelius** [comment]
Correct. I certainly believe that it is better for the units scroller, or whatever other things, to be cut, than the right bar wideness being made as wide as to accomodate it. Anyways, you are already almost there; just cutting the space currently uselessly taken by the small flag right to the units display should be fine enough for Napoleonic Empires. When the unit scroller is still too big, I suggest to cut the units display image (like those images are cut in battle windows, for example), rather than the buttons, first.

**Comment by Cernelius** [comment]
I suppose you can have a minimum wideness for the small map wideness space assigned to the sidebar (in case a mapmaker would make an overly narrow small map), depending on the map's units wideness. I would suggest 128 pixels plus the units wideness defined in map.properties.

For example, conquest_of_the_world would be 256+128=384 minimum, while Napoleonic_empires would be 48+128=176 minimum (so, still lower than the current small map, that is 200 pixels wide).

**Comment by Cernelius** [comment]
>So I would disagree that the side bar sizing is 'fine', as one existing problem I'd point to the unit stats table that is often unusable until expanded.

There is or would be really no problem with that. People can widen (once and for all the game) the right side bar to see the stats in full, that can be potentially indefinitely wide, as you can have very big numbers.

In general, we can assume the small map wideness to set the right side bar at the proper dimensions. If not, that is a map issue, yet a very subjective one (the small map would need to be made bigger for the map).

**Comment by Cernelius** [comment]
Talking about subjectiveness, I personally prefer having a narrow right sidebar, just enough to see the units and their stack numbers in the territory tab, so to leave more space for board view. I know I can have more space by hiding the right sidebar, but I often use it (mostly for actions or looking at the units listed in territory), so I don't want to keep switching it on and off. Other people may prefer wider side bars, maybe if they like seeing bigger small maps or if they look at stats often (just guessing).

**Comment by DanVanAtta** [comment]
We agree the side bar should not be bigger than it needs to be. Having to increase it's size to see content in it, is a problem. While yes, you can always make it bigger, if you *have* to make it bigger to keep things from being smushed together, there is a layout problem. Really it's a lack of considering consequences, too many items in the stats table without realization sometimes the sidebar is small. Other times when there are 3 or 4 digits in the numbers, again it's too small, a classic mistake of assuming that typical input is representative of all input.

I don't know if a super-dynamic calculation is going to be feasible, was thinking for the min will be set to something like 200px to at least accommodate the scroller controls, once some effort has been made to make those smaller. Then the size will be the greater of the 200px min or the mini-map.

**Comment by DanVanAtta** [comment]
Created a project https://github.com/triplea-game/triplea/projects/15 to track remaining TODO items
