### ISSUE TITLE
Review Process: CR CheckList?

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5643]
Question A): Does anyone have experience with using checklists for reviews, how has that gone?
Question B): Can we clarify the goals and reasons we are doing CR?
Question C): Should we create a checklist for code review items? If so, what should be on it?

The overall idea is that we would approve when we can check each item on the checklist.

Why should we do a checklist, what are the benefits?
- clarifies the goals and non-goals of review and why we are doing review. Are we gate-keeping, are we sharing knowledge, are we trying to prevent errors, all of the above?
- adds predictability for authors for what will be reviewed

In terms of mechanics, we can make the checklist part of the PR template.

Here is an example checklist to get the brainstorming started:
```
- [ ] Is the PR exhaustively tested?
- [ ] Is the updated code generally easy to understand?
- [ ] Any potential bugs?
- [ ] Are the documented conventions followed?
- [ ] Were javadocs updated to match the updated code?
- [ ] Are save-games still compatible?
- [ ] Is the code still network compatible?
```

**Comment by RoiEXLab** [comment]
A) Nope.

B) Not an easy question. In general I'd say that Code Review's purpose is mainly to avoid errors (maybe some refactoring with unintended consequences like breaking savegames etc.) and to ensure a consistent and maintainable code style?

C) I don't think a checklist will hurt, but I doubt that "abstract tasks/questions" really provide much in terms of value. "Is the PR exhaustively tested?" for example doesn't really define what "exhaustively" is, so it's easy to answer yes if you at least did some testing. Same with "Any potential bugs?", obviously nobody implements a real bug on purpose, so I'd assume that it will always be "no". I mean I get that this should get the developer thinking, but if a dev didn't think about potential bugs while actually implementing it I don't think such a simple question will change anything. However what helps me a lot is having a second look on the entire diff after creating a PR. Often I find myself noticing that I missed a small detail, or could've implemented something easier when having a second look, but then again I'm not sure if a checklist will encourage a developer to do it in-depth.
"Are save-games still compatible?" could IMO be valuable for new devs on this project if it's rephrased into a concrete task like "Verified that a savegame of <previous version> can be loaded in <current version>", because in this case I think it's harder for people to lie about it.

**Comment by DanVanAtta** [comment]
Quick point of clarification, the answer to (B) is not universal, it depends on the project. My intent is for us to clarify the goals and desired benefits of CR for us, in this project.

Some goals/benefits of CR that I can list:
- gatekeeping
- knowledge sharing
- defect detection
- maintainability (can a fresh pair eyes, a simulation of future you, read and understand)
- coding consistency
- completeness (maybe there is something you don't know about or forgot that should also be changed)

For this project, it sounds like 'defect detection' is probably up there on the list so far. It's worthwhile to also identify IMO any non-goals, like gatekeeping, perhaps of most controversy, do we want to gatekeep UI changes, or no?

**Comment by RoiEXLab** [comment]
Sounds reasonable.

TBH I think UI changes should really depend on the community inthe forum, rather than a single person.
On the other hand I don't think it'll hurt to implement something behind a beta flag and have the community test it before actually judging it.

**Comment by DanVanAtta** [comment]
:smile:  the list was kinda generic. IMO gatekeeping is an anti-goal usually. For this project, gatekeeping UI features is maybe a goal. I don't know how we balance efficiency of UI updates vs design by committee. Using beta flag removal as a gatekeeping step is maybe an okay compromise (cc:/ @panther2 )

**Comment by ron-murhammer** [comment]
I think the biggest challenge here is that right now PR reviews are really 2 things:
1. Reviewing if a feature/change is beneficial for TripleA as well as not going to cause unintended side effects (this mostly requires a lot of experience with TripleA, the code base, and our community). This unfortunately in many cases still falls to myself at the moment and I'm not sure how to solve this. I think having forum discussions around feature/updates can help mitigate this a lot but those threads often take some time for the discussion to complete which can be frustrating.
2. Reviewing the code and design which really is just applying our TripleA code standards and good design principles.

**Comment by DanVanAtta** [comment]
Thanks again for the feedback. This is proving more interesting/useful than I had thought. Re: (1), I don't know if it's just experience. Many of us have been playing TripleA for a decade plus, my first TripleA game IIRC was back in 2007 or so. I think it's perhaps more we all don't agree on what is beneficial as we have different perspectives and priorities. EG: I use the 'highlight' key a *lot*, on WaW and Cold War, I find it really helpful while I know other players never use it at all. Those players would not care if the feature were buried and made unusable. While I know that 'F' activates it, I could not ask for highlight to more available than that.

The forum discussions does invite a lot of feedback, a lot of it excellent, but you can get stuck when there is a conflict of opinion and no consensus is reached. It's not necessarily frustrating, but sometimes ineffective (ie: 'design-by-committee').

Because of the difference of opinions/perspectives, and potential for unintended side-effects, gatekeeping of UI features does seem to be an explicit goal of our CR.

> Reviewing the code and design which really is just applying our TripleA code standards and good design principles.

I would agree. We will want to eventually think about when design review happens though. Reviewing major design is difficult when you're reviewing something that is complete and tested. It's essentially the wrong time to be reviewing for design (unless there is something that is just really wrong, but even then, merging and iterating can often be a better answer). AI code fixes are a great example, if it's already done and there, it's the wrong time to be pointing out open-closed violations, or modularity changes that could be better. I think ideally all changes are done to a clean section of the code base, that we clean up before we change things, and do that as two steps, but we can't or don't always do that.

With that said, I'll hazard a first draft list for us to continue exploring to answer question (B):
- new feature and feature change gatekeeping
- knowledge sharing
- defect detection
- maintainability (can a fresh pair eyes, a simulation of future you, read and understand)
- code design
- coding consistency
- completeness (maybe there is something you don't know about or forgot that should also be changed)

**Comment by DanVanAtta** [comment]
When we go to discussing a specific check-list, if we do, we should consider the role of unit-testing review. One method of reviewing for correctness is to review the unit-tests (only). If the units tests are good, correctness should be there, and it's more likely than any manual review to find problems. It is one of the strengths of unit-tests after all. Then a benefit to reviewing the source code itself, we can review for other concerns, like readability, scalability, error handling, etc.

There is a bit of conflict though as our test coverage is somewhere ballpark 20%-25%, and a lot of code is hard to test and we do not really have a culture to add tests on every change.

**Comment by DanVanAtta** [comment]
@ron-murhammer  @RoiEXLab , yea or nay to a checklist?

**Comment by RoiEXLab** [comment]
I think I tend towards yay.
Doesn't hurt trying.

**Comment by DanVanAtta** [comment]
Closing for now, perhaps we can keep this idea in mind and give it a try in the future.
